apiVersion: v1
data:
  PGADMIN_EMAIL: admin@admin.com
  PGADMIN_PASSWORD: Aa123456
  POSTGRES_DB: todo_db
  POSTGRES_DEFAULT_USER: postgres
  POSTGRES_HOST: postgres-service
  POSTGRES_PASSWORD: Aa123456
  POSTGRES_PORT: "5432"
  POSTGRES_TABLE: tasks
  POSTGRES_USER: todo_user
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"PGADMIN_EMAIL":"admin@admin.com","PGADMIN_PASSWORD":"Aa123456","POSTGRES_DB":"todo_db","POSTGRES_DEFAULT_USER":"postgres","POSTGRES_HOST":"postgres-service","POSTGRES_PASSWORD":"Aa123456","POSTGRES_PORT":"5432","POSTGRES_TABLE":"tasks","POSTGRES_USER":"todo_user","create-db.sql":"CREATE DATABASE todo-db;\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"postgres-config","namespace":"todo-app"}}
  creationTimestamp: "2023-10-04T01:59:27Z"
  name: postgres-config
  namespace: todo-app
  resourceVersion: "57197778"
  uid: 81667c80-374f-4125-a23c-4add7361bc11
