version: "3.8"
services:
  app :
    build: ./app/
    container_name: todo-app
    network_mode: host
  db:
    image: postgres
    container_name: postgres-db
    network_mode: host
    ports:
      - 5432:5432
    env_file:
      - /app/.env