version: "3.8"
services:
  app :
    build: ./app/
    container_name: todo-app
    # network_mode: host
    links:
      - db
  db:
    build: ./database/
    container_name: todo-db
    # network_mode: host
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - /database/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../TODO-App/.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080    



