apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-15T01:16:01Z"
  finalizers:
  - batch.kubernetes.io/job-tracking
  generateName: init-database-job-
  labels:
    controller-uid: 073d6418-9e08-4611-b841-9db87f486083
    job-name: init-database-job
  name: init-database-job-fn5mb
  namespace: todo-app
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: init-database-job
    uid: 073d6418-9e08-4611-b841-9db87f486083
  resourceVersion: "59136764"
  uid: ed3a89b5-d0b1-4c27-a71b-dd7a23b9a437
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - |
      until psql -h postgres-service -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1"; do
        echo "Waiting for PostgreSQL to be ready..."
        sleep 2
      done
      psql -h postgres-service -U $POSTGRES_DEFAULT_USER -d $POSTGRES_DB -c "CREATE DATABASE $POSTGRES_DB;"
      psql -h postgres-service -U $POSTGRES_DEFAULT_USER -d $POSTGRES_DB -c "CREATE TABLE IF NOT EXISTS $POSTGRES_TABLE (id SERIAL PRIMARY KEY, tasks VARCHAR(255), status VARCHAR(255));"
      psql -h postgres-service -U $POSTGRES_DEFAULT_USER -d $POSTGRES_DB -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';"
      psql -h postgres-service -U $POSTGRES_DEFAULT_USER -d $POSTGRES_DB -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO '$POSTGRES_USER';"
    env:
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_USER
          name: postgres-config
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_DEFAULT_USER
          name: postgres-config
    - name: POSTGRES_PASSWORD
      value: POSTGRES_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_DB
          name: postgres-config
    - name: POSTGRES_TABLE
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_TABLE
          name: postgres-config
    image: postgres:latest
    imagePullPolicy: Always
    name: init-database
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-89484
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3s
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-89484
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-15T01:16:01Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-10-15T01:16:05Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-10-15T01:16:05Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-15T01:16:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://154e4d6306b6aed411b8eee440708479f8440b9c8a41a627d6eb30058f733f48
    image: docker.io/library/postgres:latest
    imageID: docker.io/library/postgres@sha256:3d9ed832906091d609cfd6f283e79492ace01ba15866b21d8a262e8fd1cdfb55
    lastState: {}
    name: init-database
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-10-15T01:16:04Z"
  hostIP: 192.168.1.250
  phase: Running
  podIP: 10.42.0.90
  podIPs:
  - ip: 10.42.0.90
  qosClass: BestEffort
  startTime: "2023-10-15T01:16:01Z"
