apiVersion: batch/v1
kind: Job
metadata:
  name: init-database-job
spec:
  template:
    spec:
      containers:
      - name: init-database
        image: postgres:latest
        command:
        - /bin/sh
        - -c
        - |
          until psql -h postgres-service -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1"; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          psql -h postgres-service -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE TABLE IF NOT EXISTS $POSTGRES_TABLE (id SERIAL PRIMARY KEY, tasks VARCHAR(255), status VARCHAR(255));"
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DEFAULT_USER
        - name: POSTGRES_PASSWORD
          value: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:  
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_TABLE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_TABLE
      restartPolicy: Never