CREATE USER todo_user WITH PASSWORD :'POSTGRES_PASSWORD';

CREATE DATABASE todo_db WITH OWNER todo_user;

\c todo_db todo_user;

CREATE TABLE tasks(
   id SERIAL PRIMARY KEY,
   task VARCHAR NOT NULL,
   ststus VARCHAR NOT NULL
);