CREATE USER IF NOT EXISTS '${POSTGRES_USER}' WITH PASSWORD '${POSTGRES_PASSWORD}';

CREATE DATABASE IF NOT EXISTS '${POSTGRES_DB}' WITH OWNER '${POSTGRES_USER}';

GRANT ALL PRIVILEGES ON DATABASE '${POSTGRES_DB}' TO '${POSTGRES_USER}';

-- \c ${POSTGRES_DB} ${POSTGRES_USER};

CREATE TABLE IF NOT EXISTS tasks(
   id SERIAL PRIMARY KEY,
   task VARCHAR NOT NULL,
   status VARCHAR NOT NULL
);