apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
spec:
  envFrom:
  - configMapRef:
      name: .env
  data:
    postgres-config: |
      # Envairoment Variables for Postgres
      # =====================================
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: : ${POSTGRES_HOST}

      # Envairoment Variables for PgAdmin
      # # ===================================
      PGADMIN_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_PASSWORD: ${PGADMIN_PASSWORD}
