apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: dvirlabs/todo-app:v2.4
        volumeMounts:
        - name: config-volume
          mountPath: /app/.env
        resources: 
          limits:
            cpu: "500m"  # Set CPU limit to 0.5 CPU cores
            memory: "256Mi"  # Set memory limit to 256 megabytes
          requests:
            cpu: "250m"  # Set CPU request to 0.1 CPU cores
            memory: "128Mi"  # Set memory request to 128 megabytes
      volumes:
      - name: config-volume
        configMap:
          name: postgres-config
      restartPolicy: Always
