apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: dvirlabs/todo-app:con-db
        volumeMounts:
        - name: config-volume
          mountPath: /app/.env
      volumes:
      - name: config-volume
        configMap:
          name: postgres-config
      restartPolicy: Always
