apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: dvirlabs/todo-app:v1.0
        env:
        - name: POSTGRES_HOST
          value: postgres-headless-service
        - name: POSTGRES_PORT
          value: 5432
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
      restartPolicy: Always